/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR              	0x40023800UL
#define RCC_CFGR_REG_ADDR          	(RCC_BASE_ADDR + 0x08UL )
#define RCC_CR_ADDR					(RCC_BASE_ADDR + 0x00)
#define GPIOA_BASE_ADDR            	0x40020000UL


int main(void)
{
	uint32_t* pRccCr = (uint32_t*) RCC_CR_ADDR;
	uint32_t *pRccCfgr =  (uint32_t*) RCC_CFGR_REG_ADDR;

	//Turning on HSE
	*pRccCr |= (1 << 16);

	//Wait for HSE to be ready since it is a crystal oscillator
	while( !(*pRccCr & (1 << 17)) );

	//Setting system clock to be HSE
	*pRccCfgr |= (1 << 0);

	//Set Mode for MC01
	*pRccCfgr &= ~(3 << 21);
	*pRccCfgr |= (2 << 21);

	//Set PreScaler
	*pRccCfgr |= ( 1 << 25);
	*pRccCfgr |= ( 1 << 26);

	uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= ( 1 << 0); //Enable GPIOA peripheral clock

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode

	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //set

	//c ) Configure the alternation function register to set the mode 0 for PA8

	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);

    /* Loop forever */
	for(;;);
}
